[付款頁面] 後端回傳錯誤時切換到錯誤訊息頁面
goodjoblife/GoodJobShare pull request #1084
Opened 2023-03-30 13:36 UTC by peteranny

Close #1066

## 這個 PR 是？ 

後端回傳錯誤訊息時，切換到錯誤訊息頁面

## 我應該如何手動測試？ 

http://localhost:3000/buy 輸入TapPay提供的錯誤card number，應該要能看到切換至錯誤頁面

2023-04-13 13:58 UTC, peteranny commented on src/components/Buy/PaymentSection/useForm.js
> +          history.push(`/buy/result/${paymentId}`);
Will not work until backend's work done.

2023-04-20 12:40 UTC, peteranny commented
https://user-images.githubusercontent.com/7566586/233368605-3cfb8104-5ef9-4ba9-ac08-7b24dbd3fc8d.mov

2023-04-27 11:49 UTC, barry800414 requested changes

2023-04-27 11:49 UTC, barry800414 commented on src/apis/payment.js
> +        error: { message },
不能假設有 error 這個欄位，反而正常付款流程會壞掉
以下是正確卡號的錯誤訊息

<img width="505" alt="Screenshot 2023-04-27 at 7 47 56 PM" src="https://user-images.githubusercontent.com/3805975/234853071-0b7b264f-eb11-48d2-935a-38f95a88649b.png">
<img width="389" alt="Screenshot 2023-04-27 at 7 48 04 PM" src="https://user-images.githubusercontent.com/3805975/234853080-28dd2af4-1bdb-46d9-8a38-e767f9062881.png">

2023-04-30 01:40 UTC, barry800414 commented
@peteranny same issue 

<img width="611" alt="Screenshot 2023-04-30 at 9 40 24 AM" src="https://user-images.githubusercontent.com/3805975/235331470-fc9c5539-0a6e-4300-8cb0-2dca7580ed55.png">

2023-04-30 01:46 UTC, barry800414 commented
And please update your branch with current latest `dev`

2023-04-30 01:49 UTC, barry800414 commented on src/components/Buy/PaymentSection/useForm.js
> +          error,
suggest to use `errorMessage` instead of error

2023-05-02 02:28 UTC, peteranny commented
更新好了，感謝

2023-05-03 16:24 UTC, barry800414 approved these changes
LGTM

2023-05-04 00:12 UTC, merged